config/routes.rb
Osb::Application.routes.draw do

  mount OsbApi::Engine => "/api"
  use_doorkeeper :scope => 'developer'

  mount DjMon::Engine => 'dj_mon'
  scope "(:locale)" do
    resources :email_templates do
      collection do
        get 'bulk_actions'
      end
    end

    resources :tasks do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
        post 'load_task_data'
      end
    end

    resources :staffs do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
        post 'load_staff_data'
      end
    end

    resources :companies do
      collection do
        get 'bulk_actions'
        post 'get_clients_and_items'
        get 'filter_companies'
        get 'undo_actions'
      end
      member do
        get 'select'
      end
    end

    resources :sub_users do
      collection do
        get 'user_settings'
      end
    end

    resources :settings

    resources :payment_terms

    resources :accounts
    resources :help
    get "reports/:report_name" => "reports#reports"
    get "reports/data/:report_name" => "reports#reports_data"
    get "reports" => "reports#index"

    get "dashboard" => "dashboard#index"
    post 'dashboard/chart_details' => "dashboard#chart_details"
    post '/invoices/send_note_only' => 'invoices#send_note_only'
    resources :payments do
      collection do
        get 'enter_payment'
        put 'update_individual_payment'
        get 'filter_payments'
        get 'bulk_actions'
        get 'undo_actions'
        get 'payments_history'
        get 'invoice_payments_history'
        post 'delete_non_credit_payments'
      end
    end
    resources :taxes do
      collection do
        get 'filter_taxes'
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    get "invoices/unpaid_invoices" => "invoices#unpaid_invoices"
    post '/payments/enter_payment'
    resources :clients do
      collection do
        post :client_detail
        get 'filter_clients'
        get 'bulk_actions'
        post 'get_last_invoice'
        post 'get_last_estimate'
        get 'undo_actions'
      end
      member do
        get 'default_currency'
      end
    end

    resources :client_contacts

    devise_for :users, :path_names => {:sign_out => 'logout'}

    devise_scope :user do
      root :to => "devise/sessions#new"
    end

    resources :items do
      collection do
        get 'filter_items'
        get 'bulk_actions'
        post 'load_item_data'
        get 'duplicate_item'
        get 'undo_actions'
      end
    end

    resources :expenses do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
      end
    end

    resources :invoice_line_items

    resources :invoices do
      resources :invoice_line_items
      collection do
        get 'filter_invoices'
        get 'bulk_actions'
        get 'undo_actions'
        post 'duplicate_invoice'
        get 'enter_single_payment'
        get 'send_invoice'
        post 'paypal_payments'
        get  'paypal_payments'
        post 'preview'
        get 'preview'
        get 'credit_card_info'
        get 'selected_currency'
      end
    end

    resources :projects do
      collection do
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    post '/invoices/delete_invoices_with_payments' => 'invoices#delete_invoices_with_payments'
    post '/invoices/dispute_invoice' => 'invoices#dispute_invoice'
    post '/invoices/pay_with_credit_card' => 'invoices#pay_with_credit_card'

    resources :recurring_profile_line_items

    resources :sent_emails

    resources :recurring_profiles do
      resources :recurring_profile_line_items
      collection do
        get 'filter_recurring_profiles'
        get 'bulk_actions'
        get 'undo_actions'
        get 'selected_currency'
      end
    end
    resources :company_profiles

    resources :client_additional_contacts

    resources :sent_emails
    resources :estimates do
      collection do
        get 'selected_currency'
        get 'send_estimate'
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    resources :logs do
      collection do
        get 'events'
        get 'update_tasks', as: 'update_tasks'
        get 'load_view'
        get 'timer'
        get 'invoice'
        post 'invoice_form'
        post 'create_invoice'

      end
    end

    resources :import_data do
      collection do
        post 'import_freshbooks_data', as: 'import_freshbooks_data'
        post 'import_quickbooks_data', as: 'import_quickbooks_data'
        get 'select_qb_data', as: 'select_qb_data'
        get :authenticate
        get :oauth_callback
      end

    end

    get ':controller(/:action(/:id))(.:format)'
  end  
end

app/models/payment_term.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
class PaymentTerm < ActiveRecord::Base
  # associations
  has_many :invoices
  has_many :recurring_profiles
end

app/controllers/payment_terms_controller.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
class
PaymentTermsController < ApplicationController
  # GET /payment_terms
  # GET /payment_terms.json
  def index
    @payment_terms = PaymentTerm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payment_terms }
    end
  end

  # GET /payment_terms/1
  # GET /payment_terms/1.json
  def show
    @payment_term = PaymentTerm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment_term }
    end
  end

  # GET /payment_terms/new
  # GET /payment_terms/new.json
  def new
    @payment_term = PaymentTerm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment_term }
    end
  end

  # GET /payment_terms/1/edit
  def edit
    @payment_term = PaymentTerm.find(params[:id])
  end

  # POST /payment_terms
  # POST /payment_terms.json
  def create
    @payment_term = PaymentTerm.new(payment_term_params)

    respond_to do |format|
      if @payment_term.save
        format.js #if params[:quick_create]
        format.json { render :json => @payment_term, :status => :created, :location => @payment_term }
      else
        format.html { render action: "new" }
        format.json { render json: @payment_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payment_terms/1
  # PUT /payment_terms/1.json
  def update
    @payment_term = PaymentTerm.find(params[:id])

    respond_to do |format|
      if @payment_term.update_attributes(payment_term_params)
        format.html { redirect_to @payment_term, notice: 'Payment term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_terms/1
  # DELETE /payment_terms/1.json
  def destroy
    @payment_term = PaymentTerm.find(params[:id])
    @payment_term.destroy

    respond_to do |format|
      format.html { redirect_to payment_terms_url }
      format.json { head :no_content }
    end
  end
  private

  def payment_term_params
    params.require(:payment_term).permit(:description, :number_of_days)
  end

end

app/helpers/payment_terms_helper.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
module PaymentTermsHelper
end

app/views/payment_terms/_form.html.erb
<%= form_for(@payment_term) do |f| %>
    <% if @payment_term.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@payment_term.errors.count, "error") %> prohibited this payment_term from being saved:</h2>

          <ul>
            <% @payment_term.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :number_of_days, t('views.payment_terms.number_of_days') %>
      <br/>
      <%= f.number_field :number_of_days %>
    </div>
    <div class="field">
      <%= f.label :description, t('views.common.description') %>
      <br/>
      <%= f.text_field :description %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/payment_terms/_new_term.html.erb
<div class="tiny_form_container">
  <div id="create_client" class="tiny_create_form">
    <div class="tiny_form_inner">

<%#= form_tag "/payment_terms/create", :id => "create_term", :remote => true do %>

      <div class="tiny_form_top">
        <div class="tiny_form_heading"><h4><%= t('views.payment_terms.add_new_payment_term') %></h4></div>
        <div class="close_btn"><%= link_to 'x', 'javascript:' %></div>
      </div>
      <!--tiny_form_top-->

      <div class="tiny_form_middle">

        <div class="fields_content_data">

          <div class="field_row">
            <div class="label_field left"><span><%= t('views.payment_terms.number_of_days') %></span></div>
            <div class="small_field">
              <%= text_field_tag "payment_term[number_of_days]", '', :required => 'required' %>
            </div>
          </div>
          <!--field_row-->

          <div class="field_row">
            <div class="label_field left single"><span><%= t('views.payment_terms.description') %></span></div>
            <div class="small_field">
              <%= text_field_tag "payment_term[description]", '', :required => 'required' %>
              <%= hidden_field_tag :quick_create %>
            </div>
          </div>
          <!--field_row-->

          <div id="clientModal" class="client-modal">
            <div class="cross_btn">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                <%= image_tag "cross.png", :size => "7x7", :alt => "" %>
              </button>
            </div>
          </div>
        </div>
        <!--fields_content_data-->
      </div>
      <!--tiny_form_middle-->

      <div class="tiny_form_btm">
<%#= submit_tag "save", :name => "save", :class => "btn_large", :style => "width:40px;" %>
<%#= submit_tag "save & ADD MORE", :name => "add_more", :class => "btn_large" %>
        <%= button_tag "save", :name => "save", :class => "btn_large tiny_btn btn_save", :style => "width:40px;" %>
        <%= button_tag "save & Add More", :name => "add_more", :class => "btn_large tiny_btn btn_save_and_add_more" %>
      </div>
      <!--tiny_form_btm-->

    </div>
    <!--tiny_form_inner-->
  </div>
  <!--tiny_create_form-->
</div><!--tiny_form_container-->
<%# end %>

app/views/payment_terms/create.js.erb
<% inlineform_action = params[:add_more] ? "inlineform:save_and_add_more" : "inlineform:save" %>
<%= "{\"action\": \"#{inlineform_action}\", \"record\": \"<option value='#{@payment_term.id}' number_of_days='#{@payment_term.number_of_days}' selected>#{@payment_term.description}</option>\"}".html_safe%>

app/views/payment_terms/edit.html.erb
<h1><%= t('views.payment_terms.editing') %></h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_term %> |
<%= link_to 'Back', payment_terms_path %>

app/views/payment_terms/index.html.erb
<h1>Listing payment_terms</h1>

<table>
  <tr>
    <th><%= t('views.payment_terms.number_of_days') %></th>
    <th><%= t('views.common.description') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @payment_terms.each do |payment_term| %>
      <tr>
        <td><%= payment_term.number_of_days %></td>
        <td><%= payment_term.description %></td>
        <td><%= link_to t('views.common.show'), payment_term %></td>
        <td><%= link_to t('helpers.links.edit'), edit_payment_term_path(payment_term) %></td>
        <td><%= link_to t('views.common.destroy'), payment_term, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to t('views.payment_terms.new'), new_payment_term_path %>

app/views/payment_terms/new.html.erb
<h1><%= t('views.payment_terms.new') %></h1>

<%= render 'form' %>

<%= link_to t('views.common.back'), payment_terms_path %>

app/views/payment_terms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('views.payment_terms.number_of_days') %>:</b>
  <%= @payment_term.number_of_days %>
</p>

<p>
  <b><%= t('views.common.description') %>:</b>
  <%= @payment_term.description %>
</p>


<%= link_to t('helpers.links.edit'), edit_payment_term_path(@payment_term) %> |
<%= link_to t('views.common.back'), payment_terms_path %>