config/routes.rb
Osb::Application.routes.draw do

  mount OsbApi::Engine => "/api"
  use_doorkeeper :scope => 'developer'

  mount DjMon::Engine => 'dj_mon'
  scope "(:locale)" do
    resources :email_templates do
      collection do
        get 'bulk_actions'
      end
    end

    resources :tasks do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
        post 'load_task_data'
      end
    end

    resources :staffs do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
        post 'load_staff_data'
      end
    end

    resources :companies do
      collection do
        get 'bulk_actions'
        post 'get_clients_and_items'
        get 'filter_companies'
        get 'undo_actions'
      end
      member do
        get 'select'
      end
    end

    resources :sub_users do
      collection do
        get 'user_settings'
      end
    end

    resources :settings

    resources :payment_terms

    resources :accounts
    resources :help
    get "reports/:report_name" => "reports#reports"
    get "reports/data/:report_name" => "reports#reports_data"
    get "reports" => "reports#index"

    get "dashboard" => "dashboard#index"
    post 'dashboard/chart_details' => "dashboard#chart_details"
    post '/invoices/send_note_only' => 'invoices#send_note_only'
    resources :payments do
      collection do
        get 'enter_payment'
        put 'update_individual_payment'
        get 'filter_payments'
        get 'bulk_actions'
        get 'undo_actions'
        get 'payments_history'
        get 'invoice_payments_history'
        post 'delete_non_credit_payments'
      end
    end
    resources :taxes do
      collection do
        get 'filter_taxes'
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    get "invoices/unpaid_invoices" => "invoices#unpaid_invoices"
    post '/payments/enter_payment'
    resources :clients do
      collection do
        post :client_detail
        get 'filter_clients'
        get 'bulk_actions'
        post 'get_last_invoice'
        post 'get_last_estimate'
        get 'undo_actions'
      end
      member do
        get 'default_currency'
      end
    end

    resources :client_contacts

    devise_for :users, :path_names => {:sign_out => 'logout'}

    devise_scope :user do
      root :to => "devise/sessions#new"
    end

    resources :items do
      collection do
        get 'filter_items'
        get 'bulk_actions'
        post 'load_item_data'
        get 'duplicate_item'
        get 'undo_actions'
      end
    end

    resources :expenses do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
      end
    end

    resources :invoice_line_items

    resources :invoices do
      resources :invoice_line_items
      collection do
        get 'filter_invoices'
        get 'bulk_actions'
        get 'undo_actions'
        post 'duplicate_invoice'
        get 'enter_single_payment'
        get 'send_invoice'
        post 'paypal_payments'
        get  'paypal_payments'
        post 'preview'
        get 'preview'
        get 'credit_card_info'
        get 'selected_currency'
      end
    end

    resources :projects do
      collection do
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    post '/invoices/delete_invoices_with_payments' => 'invoices#delete_invoices_with_payments'
    post '/invoices/dispute_invoice' => 'invoices#dispute_invoice'
    post '/invoices/pay_with_credit_card' => 'invoices#pay_with_credit_card'

    resources :recurring_profile_line_items

    resources :sent_emails

    resources :recurring_profiles do
      resources :recurring_profile_line_items
      collection do
        get 'filter_recurring_profiles'
        get 'bulk_actions'
        get 'undo_actions'
        get 'selected_currency'
      end
    end
    resources :company_profiles

    resources :client_additional_contacts

    resources :sent_emails
    resources :estimates do
      collection do
        get 'selected_currency'
        get 'send_estimate'
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    resources :logs do
      collection do
        get 'events'
        get 'update_tasks', as: 'update_tasks'
        get 'load_view'
        get 'timer'
        get 'invoice'
        post 'invoice_form'
        post 'create_invoice'

      end
    end

    resources :import_data do
      collection do
        post 'import_freshbooks_data', as: 'import_freshbooks_data'
        post 'import_quickbooks_data', as: 'import_quickbooks_data'
        get 'select_qb_data', as: 'select_qb_data'
        get :authenticate
        get :oauth_callback
      end

    end

    get ':controller(/:action(/:id))(.:format)'
  end  
end

app/models/client.rb
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
class Client < ActiveRecord::Base

  #scopes
  scope :multiple, lambda { |ids| where('id IN(?)', ids.is_a?(String) ? ids.split(',') : [*ids]) }

  # associations
  has_many :estimates
  has_many :invoices
  has_many :payments
  has_many :client_contacts, :dependent => :destroy
  has_many :projects
  accepts_nested_attributes_for :client_contacts, :allow_destroy => true
  belongs_to :company
  belongs_to :currency
  has_many :company_entities, :as => :entity
  has_many :expenses
  after_create :create_default_currency

  acts_as_archival
  acts_as_paranoid

  paginates_per 10

  def organization_name
    self[:organization_name].blank? ? self.contact_name : self[:organization_name]
  end

  def contact_name
    "#{first_name} #{last_name}"
  end

  def last_invoice
    invoices.unarchived.first.id rescue nil
  end

  def last_estimate
    estimates.unarchived.first.id rescue nil
  end

  def purchase_options
    {
        :ip => OSB::Util.local_ip,
        :billing_address => {
            :name => self.organization_name.strip! || 'Arif Khan',
            :address1 => self.address_street1 || '1 Main St',
            :city => self.city || 'San Jose',
            :state => self.province_state || 'CA',
            :country => self.country || 'US',
            :zip => self.postal_zip_code || '95131'
        }
    }
  end

  def get_credit_card(options)
    ActiveMerchant::Billing::CreditCard.new(
        :type => options[:cc_type] || 'visa',
        :first_name => options[:first_name] ||'Arif',
        :last_name => options[:last_name] ||'Khan',
        :number => options[:cc_number] ||'4650161406428289',
        :month => options[:cc_month] ||'8',
        :year => options[:cc_year] ||'2015',
        :verification_value => options[:cc_verification] ||'123'
    )
  end

  def self.archive_multiple ids
    multiple(ids).map(&:archive)
  end

  def self.delete_multiple ids
    multiple(ids).map(&:destroy)
  end

  def self.recover_archived ids
    multiple(ids).map(&:unarchive)
  end

  def self.recover_deleted ids
    multiple(ids).only_deleted.each {|client| client.restore; client.unarchive; client.client_contacts.only_deleted.map(&:restore);}
  end

  def self.filter(params)
    mappings = {active: 'unarchived', archived: 'archived', deleted: 'only_deleted'}
    method = mappings[params[:status].to_sym]
    self.send(method).page(params[:page]).per(params[:per])
  end

  def credit_payments
    credit = []
    invoices.with_deleted.each { |invoice| credit << invoice.payments.where("payment_type = 'credit'").order("created_at ASC") }
    credit << payments.first if payments.present? #include the client's initial credit
    credit.flatten
  end

  def available_credit
    client_invoice_ids = Invoice.with_deleted.where("client_id = ?", self.id).all.pluck(:id)
    # total credit

    deleted_invoices_payments = Payment.where("payment_type = 'credit' AND status IS NULL AND invoice_id in (?)", client_invoice_ids).all
    client_total_credit = deleted_invoices_payments.sum(:payment_amount)
    update_payment_status(deleted_invoices_payments)
    client_total_credit += self.payments.first.payment_amount.to_f rescue 0
    # avail credit    client_avail_credit = client_payments.sum { |f| f.payment_amount }
    client_total_credit
  end

  def update_payment_status(payments)
    payments.each do |payment|
      payment.update_attribute(:status, 'added')
    end
  end

  def client_credit
    client_invoice_ids = Invoice.with_deleted.where("client_id = ?", self.id).all.pluck(:id)
    # total credit

    deleted_invoices_payments = Payment.where("payment_type = 'credit'  AND invoice_id in (?)", client_invoice_ids).all
    client_total_credit = deleted_invoices_payments.sum(:payment_amount)

    client_total_credit += self.payments.first.payment_amount.to_f rescue 0
    # avail credit    client_avail_credit = client_payments.sum { |f| f.payment_amount }

    client_payments = Payment.where("payment_method = 'credit'  AND invoice_id in (?)", client_invoice_ids).all

    client_debit = client_payments.sum(:payment_amount)
    # Total available credit of client
    client_available_credit = client_total_credit - client_debit
    client_available_credit
  end

  def first_payment
    self.payments.first
  end

  def client_available_credit
    first_payment.try(:payment_amount)
  end

  def add_available_credit(available_credit, company_id)
    payments.build({payment_amount: available_credit, payment_type: "credit", payment_date: Date.today, company_id: company_id})
  end

  def update_available_credit(available_credit)
    payments.first.update_attribute(:payment_amount, available_credit)
  end

  def currency_symbol
    self.currency.present? ? self.currency.code : '$'
  end

  def currency_code
    self.currency.present? ? self.currency.unit : 'USD'
  end

  def self.get_clients(params)
    account = params[:user].current_account

    # get the clients associated with companies
    company_clients = Company.find(params[:company_id]).clients.send(params[:status])
    #company_clients

    # get the unique clients associated with companies and accounts
    clients = (account.clients.send(params[:status]) + company_clients).uniq

    # sort clients in ascending or descending order
    clients.sort! do |a, b|
      b, a = a, b if params[:sort_direction] == 'desc'
      params[:sort_column] = 'contact_name' if params[:sort_column].starts_with?('concat')
      a.send(params[:sort_column]) <=> b.send(params[:sort_column])
    end if params[:sort_column] && params[:sort_direction]

    Kaminari.paginate_array(clients).page(params[:page]).per(params[:per])

  end

  def create_default_currency
    return true if self.currency.present?
    currency = Currency.where(unit: 'USD').first || Currency.first
    self.currency = currency
    self.save
  end
end

app/views/estimates/_estimate.erb
<%
   no_record_message = t('views.estimates.no_estimate_msg')
if params[:status] == "archived" || @action == "recovered from archived" ||  @action == "deleted from archived"
no_record_message = t('views.estimates.no_archived_msg')
elsif params[:status] == "deleted" || @action == "recovered from deleted"
no_record_message = t('views.estimates.no_deleted_msg')
elsif params[:status] == "invoiced" || @action == "convert_to_invoiced"
no_record_message = t('views.estimates.no_invoiced_msg')
no_record_message = t('views.estimates.no_invoiced_msg')
end
%>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<% if  @estimates.length > 0 %>
    <% @estimates.each do |estimate| %>
        <tr>
          <td class="align_center"> <%= check_box_tag "estimate_ids[]", estimate.id, false, :id => "estimate_#{estimate.id}" %></td>
          <td class="align_center"><%= link_to(estimate.estimate_number, estimate_path(estimate), :class => "estimate_link #{'deleted_entry' if estimate.deleted?}") %></td>
<td class="align_left text-overflow-class" data-overflow-rows="2" ><%=  estimate.client.try(:organization_name).blank??  estimate.unscoped_client.try(:organization_name) : estimate.client.organization_name %></td>
          <td class="align_right"><%= "#{number_to_currency(estimate.estimate_total, unit: estimate.currency.present? ? estimate.currency.unit : "$")}" %></td>
          <td class="align_center"><%= estimate.estimate_date rescue "" %></td>
          <td class="align_center <%= estimate.status %>" title="<%= estimate.tooltip %>">
<span><%= estimate.status %></span></td>
          <td class="align_center">
<% if estimate.deleted_at.nil? %>
                <%= link_to t('.edit', :default => t("helpers.links.edit")),
    edit_estimate_path(estimate) %>
<% else %>
     <%= link_to t('views.common.recover', :default => t("helpers.links.recover")),
                            "javascript:;", class: "single-recover-link" %>
    <% end %>
</td>
        </tr>
<% end %>

    <% else %>
    <tr>
<td colspan="8">
    <div class="no_record_container"><%= no_record_message %></div>
      </td>
    </tr>
<% end %>

app/views/estimates/_estimate_header.html.erb
<% sort_class = params[:direction] == 'desc' ? 'sortdown' : 'sortup' %>
<tr>
  <th class="align_center not-sortable"><%= check_box_tag 'select_all' %></th>
  <th class="align_center sorting header <%= sortable_class('estimate_number') %>"><%= sortable('estimate_number', "#{t('estimate')} #") %></th>
  <th class="align_left header <%= sortable_class('clients.organization_name') %>"><%= sortable('clients.organization_name', t('client')) %></th>
  <th class="align_right header sorting {sorter:'thousands'} <%= sortable_class('estimate_total') %>"><%= sortable('estimate_total', t('views.common.total')) %></th>
  <th class="align_center header <%= sortable_class('estimate_date') %>"><%= sortable('estimate_date', t('views.common.date')) %></th>
  <th class="align_center header <%= sortable_class('status') %>"><%= sortable('status', t('views.common.status')) %></th>
  <th class="align_center not-sortable "><%= t '.actions', :default => t("helpers.actions") %></th>
</tr>

app/views/estimates/_form.html.erb
<%= nested_form_for @estimate, :html => {:class => 'estimate-form form-horizontal', :novalidate => ""} do |f| %>
    <% @parent_f = f %>

    <div class="estimate_form">
      <div class="content_middle">


        <% unless @estimate.dispute_history.blank? %>
            <div class="dispute_history">
              <div class="dispute_wrapper">
                <div class="dispute_container">
                  <div class="dispute_heading">
                    <h1><%= 'Dispute History' %></h1>
                  </div>
                  <% @estimate.dispute_history.each_with_index do |email_detail, i| %>
                      <div class="dispute_content <%= i + 1 > 2 ? "toggleable collapse" : "" %>">
                        <p><%= email_detail.content %></p>

                        <div class="dispute_content_btm respone_by_client">
                            <span class="<%= email_detail.subject == "Response to client" ? "response_by_client" : "response_by_us" %>">
                              <%= email_detail.subject == "Response to client" ? "You" : email_detail.sender %>:
                              <%= email_detail.date %>
                            </span>
                        </div>
                      </div>
                  <% end %>
                  <script>$(".dispute_content").last().css('border-bottom', 'none');</script>
                  <% if @estimate.dispute_history.length > 2 %>
                      <div class="dispute_contorl">
                        <ul>
                          <li><a class="less" href="#"><%= t('views.common.less') %></a></li>
                          <li><a class="more" href="#"><%= t('views.common.more') %></a></li>
                        </ul>
                      </div>
                  <% end %>

                  <div class="dispute_input">
                    <h4><%= 'Response to Client' %></h4>
                    <%= text_area_tag "response_to_client" %>
                    <%= hidden_field_tag :est_id, @estimate.id %>
                    <p><a href="javascript:" id="send_note_only"><%= t('views.estimates.send_this_note_only') %></a> <%= t('views.estimates.send_estimate_instructions') %></p>
                  </div>

                </div>
                <!--dispute_container-->
              </div>
              <!--dispute_wrapper-->
            </div>
            <!--dispute_history-->
        <% end %>

        <script>window.currency_symbol = "<%= @estimate.currency.present? ? @estimate.currency.unit : "$" %>"</script>
        <div class="fields_content">
          <div class="fields_content_container">
            <div class="fields_content_data new_estimate_fields custom_field">

              <div class="fields_content_left">
                <div class="field_row description">
                  <div class="label_field left single"><%= f.label :company_id, content_tag(:span, t('company')) %></div>
                  <div class="medium_field">
                    <div> <%= text_field_tag 'company', get_estimate_company_name(@estimate), :readonly => '', :class => 'company_read_only' %> </div>
                    <ul class="field_description">
                      <li><%= t('views.estimates.company_hint') %></li>
                    </ul>
                  </div>
                </div>

                <div class="field_row description">
                  <div class="label_field left single"><%= f.label :client_id, content_tag(:span, t('client')) %></div>
                  <div class="small_field">
                    <% selected_client = @client.present? ? @client.id : f.object.client_id %>
                    <%= f.select :client_id, options_for_select(load_clients(action_name, @estimate.company_id), selected: selected_client),  {:prompt => "", :include_blank => ""}, {"data-placeholder" => "Select a client...", :class => "estimate_client medium chzn-select", "data-form-container" => "clients_holder", "data-dropdown-width" => "300"} %>
                    <ul class="field_description select">
                      <li><%= t('views.estimates.client_hint') %></li>
                      <span id="last_estimate" style="display: none;"></span>
                    </ul>
                  </div>
                </div>
                <!--field_row-->
                <div class="field_row description <%= 'hide' if params[:action].eql?('new') and @estimate.currency.nil? or current_user.settings.currency.nil? or current_user.settings.currency == "Off" %>" id="estimate_currency">
                  <div class="label_field left single"><%= f.label :currency_id, content_tag(:span, t('views.common.currency')) %></div>
                  <div class="small_field">
                    <% selected_currency = (@client.present? ? @client.currency_id : f.object.currency_id) %>
                    <%= f.select :currency_id, options_for_select(Currency.all.collect{|c| ["#{c.unit} #{c.title}",c.id] }, selected: selected_currency),  {:prompt => "", :include_blank => ""}, {"data-placeholder" => t("views.common.select_estimate_currency"), :class => "estimate_currency medium chzn-select", "data-dropdown-width" => "300"} %>
                  </div>
                </div>

              </div>

              <div class="fields_content_right">

                <div class="field_row description right-fields">
                  <div class="label_field left single"><%= f.label :estimate_number,  'Estimate #' %></div>
                  <div class="small_field">
                    <%= f.text_field :estimate_number, :readonly => "", :required => "" %>
                    <ul class="field_description">
                      <li><%= t('views.estimates.auto_generated') %></li>
                    </ul>
                  </div>
                </div>
                <!--field_row-->

                <div class="field_row description right-fields">
                  <div class="label_field left single"><%= f.label :estimate_date, content_tag(:span, t('views.estimates.estimate_date')) %></div>
                  <div class="small_field">
                    <%= f.text_field :estimate_date,value: f.object.estimate_date, :required => "" %>
                  </div>
                </div>
                <!--field_row-->



                <script>$(".field_row.description").last().css('min-height', '46px');</script>

              </div>
              <!--fields_content_right-->

            </div>
            <!--fields_content_data-->
          </div>
          <!--fields_content_container-->
        </div>
        <!--fields_content-->
        <script>$(".fields_content").last().css('border-bottom', 'none');</script>

        <div class="grid_table">
          <table cellpadding="0" cellspacing="0" class="estimate_grid_fields" id="estimate_grid_fields">
            <colgroup>
              <col class="one"/>
              <col class="two"/>
              <col class="three"/>
              <col class="four"/>
              <col class="five"/>
              <col class="six"/>
              <col class="seven"/>
              <col class="eight"/>
            </colgroup>
            <tr>
              <th class="align_center">&nbsp;</th>
              <th class="align_center"><%= t('item') %></th>
              <th class="align_center"><%= t('views.common.description') %></th>
              <th class="align_center"><%= t('views.common.unit_cost') %></th>
              <th class="align_center"><%= t('views.common.qty') %></th>
              <th class="align_center"><%= t('views.common.tax') %>1</th>
              <th class="align_center"><%= t('views.common.tax') %>2</th>
              <th class="align_center"><%= t('views.estimates.line_total') %></th>
            </tr>
            <%= f.fields_for :estimate_line_items, :wrapper => false %>
            <tr style="border:none;" class="no_hover">
              <td>&nbsp</td>
              <td class="add_line_item_row" colspan="2"><%= f.link_to_add t('views.estimates.add_line_item'), :estimate_line_items, :class => "btn btn-mini", id: 'add_line_item' %></td>
            </tr>
          </table>

        </div>
        <!--grid_table-->

        <div class="grid_summary custom">
          <div class="grid_summary_content">
            <div class="grid_summary_row">
              <div class="grid_summary_title">
                <%= t('views.estimates.subtotal') %>
              </div>
              <div class="grid_summary_description">
                <%= f.hidden_field :sub_total %>
                <%= label_tag '', '', :id => 'estimate_sub_total_lbl' %>
              </div>
            </div>

            <div class="grid_summary_row discount">
              <div class="grid_summary_title">
                <!--Discount <span class="discount_percentage_lbl"></span>%-->
                Discount <%= f.select :discount_type, @discount_types, { selected: f.object.discount_type } , {:class => "discount_select chzn-select", :id => "discount_type"} %>
              </div>

              <div class="grid_summary_description custom">
                <%= f.hidden_field :discount_amount %>
                <%= label_tag '', '', :id => 'estimate_discount_amount_lbl', :style => 'font-weight:normal; display:none;' %>
                <%= f.text_field :discount_percentage, :class => "estimate_discount line_item_qtip" %>
              </div>
            </div>

            <%= f.hidden_field :tax_amount %>
            <div class="grid_summary_row taxes_total">
              <ul>
                <% @estimate.tax_detail_with_discount.map do |tax, amount| %>
                    <li><span class='grid_summary_title'><%= tax %></span>
                      <span class='grid_summary_description tax_amount'></span>
                    </li>
                <% end %>
              </ul>
            </div>

            <div class="grid_summary_row net_total">
              <div class="grid_summary_title">
                <%= t('views.estimates.net_total') %>
              </div>
              <div class="grid_summary_description">
                <%= f.hidden_field :estimate_total %>
                <%= label_tag '', '', :id => 'estimate_total_lbl', :class => 'net_total_value' %>
              </div>
            </div>
          </div>
        </div>
        <!--grid_summary-->

        <div class="fields_content_data new_estimate_fields">

          <div class="field_row textarea">
            <div class="label_field textarea"><%= f.label :notes %></div>
            <div class="large_field">
              <%= f.text_area :notes, maxlength: 400 %>
              <ul class="field_description">
                <li class="text-limit"> </li>
              </ul>
            </div>
          </div>
          <!--field_row-->

        </div>
        <!--fields_content_data-->

      </div>
      <!--content_middle-->

      <div class="content_bottom">
        <% button_text = action_name == "new" ? t('views.common.save_as_draft') : t('views.common.save') %>
        <%= f.submit t('views.estimates.send_estimate'), :class => 'btn_large submit' %>
        <%= f.submit "#{button_text}", :class => 'btn_large submit', :name => "save_as_draft" %>
        <%= link_to t("views.common.cancel"), params[:estimate_for_client] ? clients_path : estimates_path, :class => 'btn_large grey' %>
      </div>
      <!--content_bottom-->

    </div>
    <!--estimate_form-->
<% end %>

app/views/estimates/bulk_actions.js.erb
jQuery('.alert').hide();

<% if @action == "enter payment" %>
<% if @estimate_has_deleted_clients.length > 0 %>
jQuery(".alert.alert-error").show().find('span').html("Please recover clients for estimate(s) with estimate# <%= @estimate_has_deleted_clients.join(",") %> to enter payment");
<% end %>
<%else%>

<% unless params[:flag]%>
<% if @action == "archived" or @action == "deleted" %>
jQuery(".alert.alert-success").show().find('span').html("<%= escape_javascript @message %>");
<%
 if params[:destroy_archived].present?
    status = 'destroy_archived'
 elsif params[:destroy].present?
    status = 'destroy'
 else
    status = ''
 end
%>
<%else%>
jQuery(".alert.alert-success").show().find('span').html("Estimates(s) are <%= @action %> successfully.");
<% end %>
<% end %>

<%if !params[:estimate_ids].blank? && @action != "paid estimates"%>
jQuery('tbody#estimate_body').html('<%= escape_javascript(render :partial=>"estimate") %>');
<%end%>

// Enable/Disable action links(Archive,Delete,Recover). //

jQuery('#active_links').html('<%= escape_javascript render("filter_links") %>');
jQuery('#active_links a').removeClass('active');



jQuery('#select_all').attr('checked', false);

<%if @action != "paid estimates"%>
jQuery('tfoot#paging_links').html('<%= escape_javascript render :partial => "application_partials/paging", :page => params[:page] %>');
jQuery('#bulk_actions').html('<%= escape_javascript render("bulk_actions") %>');
jQuery("table.table_listing").trigger('update');
jQuery(".sent, .partial,.draft, .draft-partial, .paid, .disputed, .viewed").qtip();
//    jQuery(".text-overflow-class").ellipsis({row: 1});
<%end%>

jQuery('.top_links').hide();
<% if @action == "recovered from archived"%>
jQuery('.send').parent("li").removeClass("grid_control_sep");
jQuery('.recover_archived,.destroy_archived,.send, .convert_to_invoice').show();
jQuery('.get_archived').addClass('active');
<% elsif @action == "recovered from deleted" %>
jQuery('.recover_deleted').show().parent("li").removeClass("grid_control_sep");
jQuery('.get_deleted').addClass('active');
<% elsif @action == "deleted from archived" %>
jQuery('.send').parent("li").removeClass("grid_control_sep");
jQuery('.recover_archived,.destroy_archived,.send, .convert_to_invoice').show();
jQuery('#active_links a.get_archived').addClass('active');
<% elsif params[:destroy_archived].present?  %>
jQuery('.send').parent("li").removeClass("grid_control_sep");
jQuery('.recover_archived,.destroy_archived,.send, .convert_to_invoice').show();
jQuery('#active_links a.get_archived').addClass('active');
<%else%>
jQuery('.archive,.destroy,.convert_to_invoice,.send').show();
jQuery('.get_actives').addClass('active');
<%end%>

<%end%>
bind_deleted_entry();

app/views/estimates/show.html.erb
<%- model_class = Estimate -%>
<div class="show_estimate">

  <div class="content_top">
    <div class="primary_heading">
      <h1><%= t '.title', :default => model_class.model_name.human %>:<%= @estimate.estimate_number %></h1>
    </div>

    <div class="primary_links">
      <div id="active_links" class="grid_control_right">
        <div class="grid_control_right">
          <ul>
            <li class="grid_control_sep sep_right">
              <%= link_to t('helpers.links.edit'), edit_estimate_path(@estimate) %>
            </li>
            <!--<li><a href="#">Send</a></li>-->
            <li class="grid_control_sep sep_right">
              <%= link_to t('views.common.send'), "send_estimate?id=#{@estimate.id}" %>
            </li>
            <li class="grid_control_sep sep_right">
              <%= link_to t('views.common.pdf'), {:controller => 'estimates', :action => 'estimate_pdf', :id => @estimate.encrypted_id, :format => "pdf"}, :target => '_blank' %>
            </li>
            <li class="grid_control_sep sep_right">
              <!--<a href="#">Print</a>-->
              <%= link_to t('views.common.print'), {:controller => 'estimates', :action => 'estimate_pdf', :id => @estimate.encrypted_id, :format => "pdf"}, :target => '_blank' %>
            </li>
            <% if !@estimate.status.eql?("invoiced") %>
            <li >
              <%= link_to t('views.common.convert_to_invoice'), {:controller => 'estimates', :action => 'convert_to_invoice', :id => @estimate.id} %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <!--primary_links-->

  </div>
  <!--content_top-->

  <div class="content_middle">
    <%= render :partial => "show_estimate" %>
  </div>
  <!--content_middle-->

</div><!--show_invoice-->