config/routes.rb
Osb::Application.routes.draw do

  mount OsbApi::Engine => "/api"
  use_doorkeeper :scope => 'developer'

  mount DjMon::Engine => 'dj_mon'
  scope "(:locale)" do
    resources :email_templates do
      collection do
        get 'bulk_actions'
      end
    end

    resources :tasks do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
        post 'load_task_data'
      end
    end

    resources :staffs do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
        post 'load_staff_data'
      end
    end

    resources :companies do
      collection do
        get 'bulk_actions'
        post 'get_clients_and_items'
        get 'filter_companies'
        get 'undo_actions'
      end
      member do
        get 'select'
      end
    end

    resources :sub_users do
      collection do
        get 'user_settings'
      end
    end

    resources :settings

    resources :payment_terms

    resources :accounts
    resources :help
    get "reports/:report_name" => "reports#reports"
    get "reports/data/:report_name" => "reports#reports_data"
    get "reports" => "reports#index"

    get "dashboard" => "dashboard#index"
    post 'dashboard/chart_details' => "dashboard#chart_details"
    post '/invoices/send_note_only' => 'invoices#send_note_only'
    resources :payments do
      collection do
        get 'enter_payment'
        put 'update_individual_payment'
        get 'filter_payments'
        get 'bulk_actions'
        get 'undo_actions'
        get 'payments_history'
        get 'invoice_payments_history'
        post 'delete_non_credit_payments'
      end
    end
    resources :taxes do
      collection do
        get 'filter_taxes'
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    get "invoices/unpaid_invoices" => "invoices#unpaid_invoices"
    post '/payments/enter_payment'
    resources :clients do
      collection do
        post :client_detail
        get 'filter_clients'
        get 'bulk_actions'
        post 'get_last_invoice'
        post 'get_last_estimate'
        get 'undo_actions'
      end
      member do
        get 'default_currency'
      end
    end

    resources :client_contacts

    devise_for :users, :path_names => {:sign_out => 'logout'}

    devise_scope :user do
      root :to => "devise/sessions#new"
    end

    resources :items do
      collection do
        get 'filter_items'
        get 'bulk_actions'
        post 'load_item_data'
        get 'duplicate_item'
        get 'undo_actions'
      end
    end

    resources :expenses do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
      end
    end

    resources :invoice_line_items

    resources :invoices do
      resources :invoice_line_items
      collection do
        get 'filter_invoices'
        get 'bulk_actions'
        get 'undo_actions'
        post 'duplicate_invoice'
        get 'enter_single_payment'
        get 'send_invoice'
        post 'paypal_payments'
        get  'paypal_payments'
        post 'preview'
        get 'preview'
        get 'credit_card_info'
        get 'selected_currency'
      end
    end

    resources :projects do
      collection do
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    post '/invoices/delete_invoices_with_payments' => 'invoices#delete_invoices_with_payments'
    post '/invoices/dispute_invoice' => 'invoices#dispute_invoice'
    post '/invoices/pay_with_credit_card' => 'invoices#pay_with_credit_card'

    resources :recurring_profile_line_items

    resources :sent_emails

    resources :recurring_profiles do
      resources :recurring_profile_line_items
      collection do
        get 'filter_recurring_profiles'
        get 'bulk_actions'
        get 'undo_actions'
        get 'selected_currency'
      end
    end
    resources :company_profiles

    resources :client_additional_contacts

    resources :sent_emails
    resources :estimates do
      collection do
        get 'selected_currency'
        get 'send_estimate'
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    resources :logs do
      collection do
        get 'events'
        get 'update_tasks', as: 'update_tasks'
        get 'load_view'
        get 'timer'
        get 'invoice'
        post 'invoice_form'
        post 'create_invoice'

      end
    end

    resources :import_data do
      collection do
        post 'import_freshbooks_data', as: 'import_freshbooks_data'
        post 'import_quickbooks_data', as: 'import_quickbooks_data'
        get 'select_qb_data', as: 'select_qb_data'
        get :authenticate
        get :oauth_callback
      end

    end

    get ':controller(/:action(/:id))(.:format)'
  end  
end

app/controllers/import_data_controller.rb
class ImportDataController < ApplicationController
  #before_action :set_vendor, only: [:show, :edit, :update, :destroy]
  before_action :set_qb_service, only: [:oauth_callback]

  def index

  end

  def import_freshbooks_data
    if params[:freshbooks][:account_url].blank? or  params[:freshbooks][:api_token].blank? or params[:freshbooks][:data_filters].blank?
      redirect_to import_data_path, alert: "Please provide freshbooks account url , api key and also select alteast one module to import"
    else
      options = {}
      freshbooks_client = FreshBooks::Client.new(params[:freshbooks][:account_url], params[:freshbooks][:api_token])
      options[:company_ids] = Company.pluck(:id)
      options[:freshbooks] = freshbooks_client
      options[:current_user] = current_user
      options[:current_company_id] = get_company_id
      data_import_response = []
      params[:freshbooks][:data_filters].each do |filter|
        data_import_response <<  eval("Services::Import#{filter.humanize}Service").new.import_data(options)
      end
      if data_import_response.first.class.eql?(String)
        redirect_to import_data_path, notice: data_import_response.join('<br>').html_safe
      else
        redirect_to import_data_path, alert: data_import_response.first['error']
      end
    end

  end

  def authenticate
    callback = oauth_callback_import_data_url
    token = QB_OAUTH_CONSUMER.get_request_token(:oauth_callback => callback)
    session[:qb_request_token] = token
    # If Rails >= 4.1 you need to do this => session[:qb_request_token] = Marshal.dump(token)
    redirect_to("https://appcenter.intuit.com/Connect/Begin?oauth_token=#{token.token}") and return
  end

  def oauth_callback
    token_hash = session[:qb_request_token].get_access_token(:oauth_verifier => params[:oauth_verifier])
    #at = Marshal.load(session[:qb_request_token]).get_access_token(:oauth_verifier => params[:oauth_verifier])
    # If Rails >= 4.1 you need to do this =>  at = Marshal.load(session[:qb_request_token]).get_access_token(:oauth_verifier => params[:oauth_verifier])
    session[:token] = token_hash.token
    session[:secret] = token_hash.secret
    session[:realm_id] = params['realmId']
    session[:token_hash] = token_hash
    #options[:current_company_id] = get_company_id
    #Services::ImportQbClientService.new.import_data(options)
    #Services::ImportQbItemService.new.import_data(options)
    #Services::ImportQbEstimateService.new.import_data(options)
    #Services::ImportQbInvoiceService.new.import_data(options)
    redirect_to select_qb_data_import_data_path
    #redirect_to import_data_url, notice: 'Your QuickBooks account has been successfully linked.'
  end

  def select_qb_data
    #layout 'timer'
    render layout: 'layouts/timer'
  end

  def import_quickbooks_data
    options = {}
    options[:realm_id] = session[:realm_id]
    options[:token_hash] = session[:token_hash]
    options[:current_company_id] = get_company_id
    #Services::ImportQbClientService.new.import_data(options)
    #Services::ImportQbItemService.new.import_data(options)
    #Services::ImportQbEstimateService.new.import_data(options)
    #Services::ImportQbInvoiceService.new.import_data(options)
    data_import_response = []
    params[:quickbooks][:data_filters].each do |filter|
      data_import_response <<  eval("Services::ImportQb#{filter.humanize}Service").new.import_data(options)
    end

    redirect_to import_data_url, notice: 'Your QuickBooks account has been successfully linked.'

  end

  private

  def set_qb_service
    oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, session[:token], session[:secret])
    @vendor_service = Quickbooks::Service::Vendor.new
    @vendor_service.access_token = oauth_client
    @vendor_service.company_id = session[:realm_id]
  end

end

app/views/import_data/_fb_connect.html.erb
<div id='fb_link'>
    <a href="javascript:;" data-toggle = "modal" data-target = "#freshModal">
      <img src="/assets/freshbooks.png" class="img-import" alt="freshbooks">
    </a>
</div>

app/views/import_data/_freshbooks_popup.html.erb
<div id="freshModal" class="modal hide fad" tabindex="-1" role="dialog" aria-labelledby="freshModalLabel" aria-hidden="true">
  <div class="model_grey_container">
    <div class="modal-header">
      <h1>Import Data from your Freshbooks Account</h1>

      <div class="cross_btn" style="margin:-50px -1px 0 0">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          <%= image_tag "cross.png", :size => "7x7", :alt => "" %>
        </button>
      </div>
    </div>
    <div class="modal-body">
      <%= form_for :freshbooks, url: import_freshbooks_data_import_data_path,  :html => {novalidate: "", class: "form-horizontal"} do |f| %>
          <div class="fields_content">
            <div class="fields_content_container">
              <div>
                <div class="field_row">
                  <div class="label_field left single"><span> Account URL </span></div>
                  <div class="large_field">
                    <%= f.text_field :account_url, :required => "required"  %>
                  </div>
                </div>
                <!--field_row-->

                <div class="field_row">
                  <div class="label_field left single"><span>  API Token </span></div>
                  <div class="large_field">
                    <%= f.text_field :api_token, :required => "required" %>
                  </div>
                </div>

                <div class="field_row">
                  <div>
                    <span>  Select module to import</span>
                  </div>
                  <% Services::Freshbook::DATA_MODULES.each do |a_value| %>
                    <div class="data-import-module checkbox">
                      <label for="freshbooks_data_filters_<%= a_value.downcase %>">
                        <%= f.check_box(:data_filters, {multiple: true, checked: "checked"}, a_value.downcase, nil) %>
                        <%= a_value %>
                      </label>
                    </div>
                  <% end %>
                </div>

              </div>
            </div>

              <!--field_row-->
          </div>
      <% end %>
    </div>

    <div class="footer ">
        <%= submit_tag "Submit", :class => "btn_large submit model-submit-btn" %>
        <a class="btn_large grey" href="#" data-dismiss="modal">cancel</a>
    </div>
  </div>
</div>


<script>
  $(".model-submit-btn").click(function (){
      $(this).parents().find("form").submit();
  })
</script>

app/views/import_data/_qb_connect.html.erb
<div id='qb_link'>
    <ipp:connectToIntuit></ipp:connectToIntuit>
    <%= yield %>
    <script type="text/javascript" src="https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js"></script>
    <script>
    intuit.ipp.anywhere.setup({menuProxy: '/path/to/blue-dot', grantUrl: '<%= authenticate_import_data_url %>'});
    </script>
</div>

app/views/import_data/index.html.erb
<div class="import_data">
    <div class="content_top">
        <div class="primary_heading">
            <h1>
                <%= t('views.import_data.import_data') %>
            </h1>
        </div>
    </div>
    <div id='import_links'>
        <%= render partial: 'fb_connect' %>
        <%= render partial: 'qb_connect' %>
    </div>
</div>

<%= render partial: 'freshbooks_popup'%>

app/views/import_data/select_qb_data.html.erb
<div id="freshModal" class="modal fad" tabindex="-1" role="dialog" aria-labelledby="freshModalLabel" aria-hidden="false">
  <div class="model_grey_container">
    <div class="modal-header">
      <h1>Import Data from your Quickbooks Account</h1>
    </div>
    <div class="modal-body">
      <%= form_for :quickbooks, url: import_quickbooks_data_import_data_path,  :html => {novalidate: "", class: "form-horizontal"} do |f| %>
          <div class="fields_content">
            <div class="fields_content_container">
              <div>

                <div class="field_row">
                  <div>
                    <span>  Select modules to import</span>
                  </div>
                  <% Services::Quickbook::DATA_MODULES.each do |a_value| %>
                      <div class="data-import-module checkbox">
                        <label for="quickbooks_data_filters_<%= a_value.downcase %>">
                          <%= f.check_box(:data_filters, {multiple: true, checked: "checked"}, a_value.downcase, nil) %>
                          <%= a_value %>
                        </label>
                      </div>
                  <% end %>
                </div>

              </div>
            </div>

            <!--field_row-->
          </div>
      <% end %>
    </div>

    <div class="footer ">
      <%= submit_tag "Submit", :class => "btn_large submit model-submit-btn" %>
      <a class="btn_large grey" href="#" data-dismiss="modal">cancel</a>
    </div>
  </div>
</div>

<script>
    $(".model-submit-btn").click(function (){
        $(this).parents().find("form").submit();
    })
</script>