config/routes.rb
Osb::Application.routes.draw do

  mount OsbApi::Engine => "/api"
  use_doorkeeper :scope => 'developer'

  mount DjMon::Engine => 'dj_mon'
  scope "(:locale)" do
    resources :email_templates do
      collection do
        get 'bulk_actions'
      end
    end

    resources :tasks do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
        post 'load_task_data'
      end
    end

    resources :staffs do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
        post 'load_staff_data'
      end
    end

    resources :companies do
      collection do
        get 'bulk_actions'
        post 'get_clients_and_items'
        get 'filter_companies'
        get 'undo_actions'
      end
      member do
        get 'select'
      end
    end

    resources :sub_users do
      collection do
        get 'user_settings'
      end
    end

    resources :settings

    resources :payment_terms

    resources :accounts
    resources :help
    get "reports/:report_name" => "reports#reports"
    get "reports/data/:report_name" => "reports#reports_data"
    get "reports" => "reports#index"

    get "dashboard" => "dashboard#index"
    post 'dashboard/chart_details' => "dashboard#chart_details"
    post '/invoices/send_note_only' => 'invoices#send_note_only'
    resources :payments do
      collection do
        get 'enter_payment'
        put 'update_individual_payment'
        get 'filter_payments'
        get 'bulk_actions'
        get 'undo_actions'
        get 'payments_history'
        get 'invoice_payments_history'
        post 'delete_non_credit_payments'
      end
    end
    resources :taxes do
      collection do
        get 'filter_taxes'
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    get "invoices/unpaid_invoices" => "invoices#unpaid_invoices"
    post '/payments/enter_payment'
    resources :clients do
      collection do
        post :client_detail
        get 'filter_clients'
        get 'bulk_actions'
        post 'get_last_invoice'
        post 'get_last_estimate'
        get 'undo_actions'
      end
      member do
        get 'default_currency'
      end
    end

    resources :client_contacts

    devise_for :users, :path_names => {:sign_out => 'logout'}

    devise_scope :user do
      root :to => "devise/sessions#new"
    end

    resources :items do
      collection do
        get 'filter_items'
        get 'bulk_actions'
        post 'load_item_data'
        get 'duplicate_item'
        get 'undo_actions'
      end
    end

    resources :expenses do
      collection do
        get 'bulk_actions'
        get 'filter_items'
        get 'undo_actions'
      end
    end

    resources :invoice_line_items

    resources :invoices do
      resources :invoice_line_items
      collection do
        get 'filter_invoices'
        get 'bulk_actions'
        get 'undo_actions'
        post 'duplicate_invoice'
        get 'enter_single_payment'
        get 'send_invoice'
        post 'paypal_payments'
        get  'paypal_payments'
        post 'preview'
        get 'preview'
        get 'credit_card_info'
        get 'selected_currency'
      end
    end

    resources :projects do
      collection do
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    post '/invoices/delete_invoices_with_payments' => 'invoices#delete_invoices_with_payments'
    post '/invoices/dispute_invoice' => 'invoices#dispute_invoice'
    post '/invoices/pay_with_credit_card' => 'invoices#pay_with_credit_card'

    resources :recurring_profile_line_items

    resources :sent_emails

    resources :recurring_profiles do
      resources :recurring_profile_line_items
      collection do
        get 'filter_recurring_profiles'
        get 'bulk_actions'
        get 'undo_actions'
        get 'selected_currency'
      end
    end
    resources :company_profiles

    resources :client_additional_contacts

    resources :sent_emails
    resources :estimates do
      collection do
        get 'selected_currency'
        get 'send_estimate'
        get 'bulk_actions'
        get 'undo_actions'
      end
    end

    resources :logs do
      collection do
        get 'events'
        get 'update_tasks', as: 'update_tasks'
        get 'load_view'
        get 'timer'
        get 'invoice'
        post 'invoice_form'
        post 'create_invoice'

      end
    end

    resources :import_data do
      collection do
        post 'import_freshbooks_data', as: 'import_freshbooks_data'
        post 'import_quickbooks_data', as: 'import_quickbooks_data'
        get 'select_qb_data', as: 'select_qb_data'
        get :authenticate
        get :oauth_callback
      end

    end

    get ':controller(/:action(/:id))(.:format)'
  end  
end

app/models/invoice_line_item.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
class InvoiceLineItem < ActiveRecord::Base
  # associations
  belongs_to :invoice
  belongs_to :estimate
  belongs_to :item
  belongs_to :tax1, :foreign_key => 'tax_1', :class_name => 'Tax'
  belongs_to :tax2, :foreign_key => 'tax_2', :class_name => 'Tax'

  # archive and delete
  acts_as_archival
  acts_as_paranoid

  attr_accessor :tax_one, :tax_two

  def unscoped_item
    Item.unscoped.find_by_id self.item_id
  end
end

app/controllers/invoice_line_items_controller.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
class InvoiceLineItemsController < ApplicationController
  #before_filter :authenticate_user!
  # GET /invoice_line_items
  # GET /invoice_line_items.json
  def index
    @invoice_line_items = InvoiceLineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoice_line_items }
    end
  end

  # GET /invoice_line_items/1
  # GET /invoice_line_items/1.json
  def show
    @invoice_line_item = InvoiceLineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoice_line_item }
    end
  end

  # GET /invoice_line_items/new
  # GET /invoice_line_items/new.json
  def new
    @invoice_line_item = InvoiceLineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice_line_item }
    end
  end

  # GET /invoice_line_items/1/edit
  def edit
    @invoice_line_item = InvoiceLineItem.find(params[:id])
  end

  # POST /invoice_line_items
  # POST /invoice_line_items.json
  def create
    @invoice_line_item = InvoiceLineItem.new(invoice_line_item_params)

    respond_to do |format|
      if @invoice_line_item.save
        format.html { redirect_to @invoice_line_item, notice: 'Invoice line item was successfully created.' }
        format.json { render json: @invoice_line_item, status: :created, location: @invoice_line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invoice_line_items/1
  # PUT /invoice_line_items/1.json
  def update
    @invoice_line_item = InvoiceLineItem.find(params[:id])

    respond_to do |format|
      if @invoice_line_item.update_attributes(invoice_line_item_params)
        format.html { redirect_to @invoice_line_item, notice: 'Invoice line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoice_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_line_items/1
  # DELETE /invoice_line_items/1.json
  def destroy
    @invoice_line_item = InvoiceLineItem.find(params[:id])
    @invoice_line_item.destroy

    respond_to do |format|
      format.html { redirect_to invoice_line_items_url }
      format.json { head :no_content }
    end
  end

  private

  def invoice_line_item_params
    params.require(:invoice_line_item).permit(:invoice_id, :item_description, :item_id, :item_name, :item_quantity, :item_unit_cost, :tax_1, :tax_2)
  end

end

app/helpers/invoice_line_items_helper.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
module InvoiceLineItemsHelper
end

app/views/invoice_line_items/_form.html.erb
<%= form_for(@invoice_line_item) do |f| %>
    <% if @invoice_line_item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@invoice_line_item.errors.count, "error") %> prohibited this invoice_line_item from being
            saved:</h2>

          <ul>
            <% @invoice_line_item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :item_id, t('views.invoice_line_item.item') %>
      <br/>
      <%= f.number_field :item_id %>
      <%= collection_select :invoice_line_item, :item_id, Item.all, :id, :item_name, :prompt => "Select an item" %>
    </div>
    <div class="field">
      <%= f.label :item_name, t('views.invoice_line_item.name') %>
      <br/>
      <%= f.text_field :item_name %>
    </div>
    <div class="field">
      <%= f.label :item_description, t('views.invoice_line_item.description') %>
      <br/>
      <%= f.text_field :item_description %>
    </div>
    <div class="field">
      <%= f.label :item_unit_cost, t('views.invoice_line_item.unit_cost') %>
      <br/>
      <%= f.text_field :item_unit_cost %>
    </div>
    <div class="field">
      <%= f.label :item_quantity, t('views.invoice_line_item.quantity') %>
      <br/>
      <%= f.text_field :item_quantity %>
    </div>
    <div class="field">
      <%= f.label :tax_1, t('views.invoice_line_item.tax_1') %>
      <br/>
      <%= f.number_field :tax_1 %>
    </div>
    <div class="field">
      <%= f.label :tax_2, t('views.invoice_line_item.tax_2') %>
      <br/>
      <%= f.number_field :tax_2 %>
    </div>
    <%= f.link_to_remove "x" %>
    <%= f.link_to_add "+", :invoice_line_items %>
<% end %>

app/views/invoice_line_items/edit.html.erb
<h1>Editing invoice_line_item</h1>

<%= render 'form' %>

<%= link_to t('views.common.show'), @invoice_line_item %> |
<%= link_to t('views.common.back'), invoice_line_items_path %>

app/views/invoice_line_items/index.html.erb
<h1>Listing invoice_line_items</h1>

<table>
  <tr>
    <th><%= t('invoice') %></th>
    <th><%= t('views.common.item') %></th>
    <th><%= t('views.invoice_line_item.name') %></th>
    <th><%= t('views.invoice_line_item.description') %></th>
    <th><%= t('views.invoice_line_item.unit_cost') %></th>
    <th><%= t('views.invoice_line_item.quantity') %></th>
    <th><%= t('views.invoice_line_item.tax_1') %></th>
    <th><%= t('views.invoice_line_item.tax_2') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @invoice_line_items.each do |invoice_line_item| %>
      <tr>
        <td><%= invoice_line_item.invoice_id %></td>
        <td><%= invoice_line_item.item_id %></td>
        <td><%= invoice_line_item.item_name %></td>
        <td><%= invoice_line_item.item_description %></td>
        <td><%= invoice_line_item.item_unit_cost %></td>
        <td><%= invoice_line_item.item_quantity %></td>
        <td><%= invoice_line_item.tax_1 %></td>
        <td><%= invoice_line_item.tax_2 %></td>
        <td><%= link_to t('views.common.show'), invoice_line_item %></td>
        <td><%= link_to t('helpers.links.edit'), edit_invoice_line_item_path(invoice_line_item) %></td>
        <td><%= link_to t('views.common.destroy'), invoice_line_item, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to t('views.invoice_line_item.new'), new_invoice_line_item_path %>

app/views/invoice_line_items/new.html.erb
<h1><%= t('views.invoice_line_item.new') %></h1>

<%= render 'form' %>

<%= link_to t('views.common.back'), invoice_line_items_path %>

app/views/invoice_line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('invoice') %>:</b>
  <%= @invoice_line_item.invoice_id %>
</p>

<p>
  <b><%= t('views.invoice_line_item.item') %>:</b>
  <%= @invoice_line_item.item_id %>
</p>

<p>
  <b><%= t('views.invoice_line_item.name') %>:</b>
  <%= @invoice_line_item.item_name %>
</p>

<p>
  <b><%= t('views.invoice_line_item.description') %>:</b>
  <%= @invoice_line_item.item_description %>
</p>

<p>
  <b><%= t('views.invoice_line_item.unit_cost') %>:</b>
  <%= @invoice_line_item.item_unit_cost %>
</p>

<p>
  <b><%= t('views.invoice_line_item.quantity') %>:</b>
  <%= @invoice_line_item.item_quantity %>
</p>

<p>
  <b><%= t('views.invoice_line_item.tax_1') %>:</b>
  <%= @invoice_line_item.tax_1 %>
</p>

<p>
  <b><%= t('views.invoice_line_item.tax_2') %>:</b>
  <%= @invoice_line_item.tax_2 %>
</p>


<%= link_to t('helpers.links.edit'), edit_invoice_line_item_path(@invoice_line_item) %> |
<%= link_to t('views.common.back'), invoice_line_items_path %>